name: darkoveljaca
favicon: null
layout_spectrum: 0.5808733133599162
typography_spectrum: 0.23022767226211727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1095249648205936
  lightness: 0.5706472494639456
  saturation: 0.5419402604456991
  rhythmicContrast: 0.1756689774338156
purpose: []
